library(ggplot2)
p <- ggplot(mtcars) + geom_point(aes(x = wt, y = mpg))
p + theme_gray() # 默认
p + theme_bw()
p + theme_linedraw()
p + theme_light()
p + theme_dark()
p + theme_minimal()
p + theme_classic()
p + theme_void()